# Generated by Django 6.0.5 on 2026-07-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('mandatory_internship', 'Mandatory Internship'), ('non_mandatory_internship_credit', 'Non Mandatory Internship Credit'), ('professional_practice_credit', 'Professional Practice Credit'), ('supervisor_evaluation', 'Supervisor Evaluation')], max_length=60),
        ),
    ]
