GROUP_STUDENT = "Student"
GROUP_PROFESSOR = "Teacher"
GROUP_COORDINATOR = "Coordinator"
GROUP_SUPERVISOR = "Supervisor"

DEFAULT_GROUPS = [
    GROUP_STUDENT,
    GROUP_PROFESSOR,
    GROUP_COORDINATOR,
    GROUP_SUPERVISOR,
]
