# Generated by Django 6.0.5 on 2026-06-30 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=150)),
                ('professional_registration', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('company_document', models.CharField(max_length=20)),
                ('company_professional_registration', models.CharField(blank=True, max_length=100)),
                ('company_zip_code', models.CharField(max_length=9)),
                ('company_address', models.CharField(max_length=255)),
                ('company_address_number', models.CharField(max_length=20)),
                ('company_address_complement', models.CharField(blank=True, max_length=150)),
                ('company_neighborhood', models.CharField(max_length=150)),
                ('company_city', models.CharField(max_length=150)),
                ('company_state', models.CharField(max_length=2)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone_number', models.CharField(max_length=30)),
                ('company_business_activity', models.CharField(max_length=150)),
                ('company_business_activity_other', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name', 'user__first_name', 'user__last_name'],
            },
        ),
    ]
