# Generated by Django 6.0.5 on 2026-06-15 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('documents_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Ativo'), (2, 'Finalizado'), (3, 'Cancelado')], default=0)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_begin', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='students.student')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('user_admin', models.ForeignKey(db_column='UserAdminID', on_delete=django.db.models.deletion.PROTECT, related_name='admin_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'Documents',
            },
        ),
    ]
