# Generated by Django 6.0.5 on 2026-06-15 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocActivity',
            fields=[
                ('doc_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Criado'), (1, 'Atualizado'), (2, 'Aprovado'), (3, 'Rejeitado')], default=0)),
                ('description', models.CharField(max_length=512)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('alter_by_user', models.ForeignKey(db_column='AlterByUserID', on_delete=django.db.models.deletion.PROTECT, related_name='doc_activities', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(db_column='DocumentsID', on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='documents.documents')),
            ],
            options={
                'verbose_name': 'Doc Activity',
                'verbose_name_plural': 'Doc Activities',
                'db_table': 'DocActivity',
                'ordering': ['-server_timestamp'],
            },
        ),
    ]
