# Generated by Django 6.0.5 on 2026-06-07 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('documents_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('status', models.IntegerField()),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_begin', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.IntegerField()),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('user_admin', models.ForeignKey(db_column='UserAdminID', on_delete=django.db.models.deletion.PROTECT, related_name='admin_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='DocActivity',
            fields=[
                ('doc_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.IntegerField()),
                ('alter_by_user', models.ForeignKey(db_column='AlterByUserID', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(db_column='DocumentsID', on_delete=django.db.models.deletion.PROTECT, to='students.documents')),
            ],
            options={
                'verbose_name': 'Doc Activity',
                'verbose_name_plural': 'Doc Activities',
                'db_table': 'DocActivity',
            },
        ),
    ]
